In [6]:
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [7]:
df=pd.read_csv('TSLA_messy.csv')
print(df.head())
df.info()
df['Date']=pd.to_datetime(df['Date'], format='mixed', errors='coerce')
df.isnull().sum()
numeric_columns = ['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume']
for column in numeric_columns:
    df[column] = pd.to_numeric(df[column], errors='coerce')
df.info()
df.isnull().sum()

        Date       Open        High         Low       Close   Adj Close  \
0  9/16/2011      4.956    5.168000    4.898000    5.160000    5.160000
1  1/23/2012      5.362    5.442000    5.320000    5.354000    5.354000
2  1/13/2021  852.76001  860.469971  832.000000  854.409973  854.409973
3  6/28/2011      5.558    5.650000    5.534000    5.622000    5.622000
4  9/11/2015     49.528   50.048000   48.945999   50.048000   50.048000

     Volume
0   7085500
1   2973000
2  33312500
3   4446000
4  11754000
<class 'pandas.DataFrame'>
RangeIndex: 2967 entries, 0 to 2966
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2967 non-null   str
 1   Open       2964 non-null   str
 2   High       2964 non-null   float64
 3   Low        2964 non-null   float64
 4   Close      2964 non-null   float64
 5   Adj Close  2964 non-null   float64
 6   Volume     2963 non-null   str
dtypes: float64(4), str(3)
memory usage: 162.4 KB
<class 'pandas.DataFrame'>
RangeIndex: 2967 entries, 0 to 2966
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2965 non-null   datetime64[us]
 1   Open       2963 non-null   float64
 2   High       2964 non-null   float64
 3   Low        2964 non-null   float64
 4   Close      2964 non-null   float64
 5   Adj Close  2964 non-null   float64
 6   Volume     2962 non-null   float64
dtypes: datetime64[us](1), float64(6)
memory usage: 162.4 KB

Date         2
Open         4
High         3
Low          3
Close        3
Adj Close    3
Volume       5
dtype: int64

In [8]:
mean_values = df[numeric_columns].mean()
median_values = df[numeric_columns].median()
mode_values = df[numeric_columns].mode().iloc[0]

print("Mean:")
print(mean_values)

print("\nMedian:")
print(median_values)

print("\nMode:")
print(mode_values)

Mean:
Open         1.423307e+02
High         1.454208e+02
Low          1.388129e+02
Close        1.419759e+02
Adj Close    1.419759e+02
Volume       3.126108e+07
dtype: float64

Median:
Open         4.667600e+01
High         4.749300e+01
Low          4.582500e+01
Close        4.654500e+01
Adj Close    4.654500e+01
Volume       2.482425e+07
dtype: float64

Mode:
Open         5.600
High         5.600
Low          5.460
Close        5.484
Adj Close    5.484
Volume       0.000
Name: 0, dtype: float64

In [9]:
df[numeric_columns] = df[numeric_columns].fillna(median_values)
df.isnull().sum()

Date         2
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [10]:
df[df['Date'].isna()]

,Date,Open,High,Low,Close,Adj Close,Volume
1550,NaT,1189.550049,1208.0,1123.050049,1149.589966,1149.589966,33416100.0
1740,NaT,1189.550049,1208.0,1123.050049,1149.589966,1149.589966,33416100.0

In [11]:
df = df.dropna(subset=['Date'])
df.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [12]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [13]:
df=df.sort_values(by='Date')
df.head()

           Date   Open   High    Low  Close  Adj Close      Volume
2180 2010-06-29  3.800  5.000  3.508  4.778      4.778  93831500.0
2798 2010-06-30  5.158  6.084  4.660  4.766      4.766  85935500.0
2197 2010-07-01  5.000  5.184  4.054  4.392      4.392  41094000.0
179  2010-07-02  4.600  4.620  3.742  3.840      3.840  25699000.0
36   2010-07-06  4.000  4.000  3.166  3.222      3.222  34334500.0

In [14]:
df=df.sort_values(by='Date', ascending=False)
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume
748,2022-03-24,1009.729980,1024.489990,988.799988,1013.919983,1013.919983,22901900.0
2764,2022-03-23,979.940002,1040.699951,976.400024,999.109985,999.109985,40225400.0
1056,2022-03-22,930.000000,997.859985,921.750000,993.979980,993.979980,35289500.0
1333,2022-03-21,914.979980,942.849976,907.090027,921.159973,921.159973,27327200.0
1830,2022-03-18,874.489990,907.849976,867.390015,905.390015,905.390015,33408500.0

In [15]:
df = df.reset_index(drop=True)
df.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2022-03-24,1009.729980,1024.489990,988.799988,1013.919983,1013.919983,22901900.0
1,2022-03-23,979.940002,1040.699951,976.400024,999.109985,999.109985,40225400.0
2,2022-03-22,930.000000,997.859985,921.750000,993.979980,993.979980,35289500.0
3,2022-03-21,914.979980,942.849976,907.090027,921.159973,921.159973,27327200.0
4,2022-03-18,874.489990,907.849976,867.390015,905.390015,905.390015,33408500.0
5,2022-03-17,830.989990,875.000000,825.719971,871.599976,871.599976,22194300.0
6,2022-03-16,809.000000,842.000000,802.260010,840.229980,840.229980,28009600.0
7,2022-03-15,775.270020,805.570007,756.570007,801.890015,801.890015,22280400.0
8,2022-03-14,780.609985,800.700012,756.039978,766.369995,766.369995,23717400.0
9,2022-03-11,840.200012,843.799988,793.770020,795.349976,795.349976,22272800.0

In [16]:
df.describe()

,Date,Open,High,Low,Close,Adj Close,Volume
count,2958,2958.000000,2958.000000,2958.000000,2958.000000,2958.000000,2.958000e+03
mean,2016-05-10 10:03:39.066937,141.616423,144.727558,138.169443,141.316992,141.316992,3.126772e+07
min,2010-06-29 00:00:00,-5.196000,3.326000,-48.127998,-66.725998,-66.725998,-2.500000e+05
25%,2013-06-05 06:00:00,19.789499,20.504000,19.082499,19.573000,19.573000,1.305900e+07
50%,2016-05-10 12:00:00,46.675999,47.493000,45.825001,46.545000,46.545000,2.482425e+07
75%,2019-04-17 18:00:00,68.026499,69.233002,66.879499,68.001501,68.001501,3.971275e+07
max,2022-03-24 00:00:00,10417.099610,10546.700440,9950.000000,9956.500240,9956.500240,3.046940e+08
std,NaN,312.391118,318.417974,302.361661,307.366458,307.366458,2.799247e+07

In [ ]:
# considering he median is the better choice because the mean is much higher than the median, 
# which suggests some large values are pulling the mean upward. Median is less affected by extreme values.